[package]
name = "robloxiandemo/cleanser"
description = "A cleaning class akin to that of Quenty's Maid and Small's Janitor, which has built-in compatibility for usage with Wally."
version = "0.1.8"
license = "MIT"
authors = ["Demo (https://github.com/RobloxianDemo)"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"